### ISSUE TITLE
프로젝트 주제 정하기

### ISSUE THREAD

**Issue by gyseong** [JJOGyeongS/-vegetable_project#1]
**프로젝트 여러 주제 후보 중에 하나를 정해요**

**Comment by gyseong** [comment]
알바 시간 출퇴근 모니터링 시스템
qr코드를  만들어서 출퇴근을 찍고 근무 시간을 모니터링하여 알바생마다 급여를 계산하여 월말에 금액을 알려주는 프로그램

**Comment by Kim-yejin-yj** [comment]
채소값 모니터링 - 일기 예보로 채솟값의 폭등과 폭락을 예측함 -> 사재기 방지?, (공동구매) 농장은 하자 있는 상품을 싼 값에 팔게 되고, 소비자는 싼 값으로 사게 되는 프로그램

**Comment by Kim-yejin-yj** [comment]
야생동물 모니터링 - 농가에 침입해오는 야생동물을 감지하여 앱으로 알려주고 퇴치해주는 프로그램

**Comment by gyseong** [comment]
말벌 탐지기 프로그램
딥러닝으로 말벌을 탐지하여 말벌이 자주 나오는 시간을 모니터링하여 양봉업자들에게 도움을 주는 프로그램

**Comment by Kim-yejin-yj** [comment]
채소값 주제는 찾아보니까 지역별로 값이 다 다르네요. 지역별로 이것들을 추합해서 평균 내는게 쉽지 않을 것 같아요. 
어떻게 생각하세요??

**Comment by gyseong** [comment]
아예 한 도만 선택해서 하면 너무 제한적이겠죠..?

**Comment by gyseong** [comment]
아예 안동대학교에 말벌 탐지 딥러닝 기술을 사용해도 되냐고 물어보면 좀 오바일까요? 저희가 이거 딥러닝으로 하면 개발하는데 꽤 오래걸릴거 같아요

**Comment by gyseong** [comment]
식품 과대 광고 모니터링
식품 광고들을 모니터링하여 이 제품이 과거 과대 광고로 신고를 당했는지 소비자에게 알려주어 소비자가 현명한 판단을 하게 하는 프로그램
