### ISSUE TITLE
api 키를 판매자만 준다네요.. 

### ISSUE THREAD

**Issue by Kim-yejin-yj** [JJOGyeongS/-vegetable_project#12]
크롤링으로 바꿔야할까요..

**Comment by gyseong** [comment]
크롤링으로 바꿔야 할 것 같습니다
이 링크는 파이썬으로 쿠팡 크롤링하는 예제에요 법적인 문제는 되지 않는 것 같아요

https://goodthings4me.tistory.com/562

**Comment by gyseong** [comment]
가격 비교 사이트를 구현할 때 법적인 문제가 되지 않게 상품 리스트 정보를 보여주는 형식으로 해야될 것 같네요..

**Comment by Kim-yejin-yj** [comment]
그게 좋겠네요
