### ISSUE TITLE
최종 발표 ppt에 어떤 내용들이 들어가야 되나요?

### ISSUE THREAD

**Issue by Kim-yejin-yj** [JJOGyeongS/-vegetable_project#15]

**Comment by Kim-yejin-yj** [comment]
1. 필요성
2. problem
3. 차별성
4. solution 
5. 결과물 시연영상
6. 한계점 및 개선해야할 사항 

이렇게만 넣을까요?

**Comment by Kim-yejin-yj** [comment]
피피티 첫 슬라이드에 우리 로고 넣어도 좋을 것 같네요

**Comment by gyseong** [comment]
solution 관련 부분 DB 사진 찍어서 보내드릴게요

**Comment by gyseong** [comment]
한계점 및 개선사항은 제가 작성해서 3시까지 보내드리겠습니다 나머지는 중간 발표에 있는 내용 그대로 가도 될거 같아요

**Comment by Kim-yejin-yj** [comment]
넵 알겠습니당
