### ISSUE TITLE
input,output,problem,solution 정하기

### ISSUE THREAD

**Issue by gyseong** [JJOGyeongS/-vegetable_project#2]
차별성까지 정합시다

**Comment by gyseong** [comment]
[KAMIS](https://www.kamis.or.kr/customer/main/main.do)에서 농수산물 시세 데이터를 확보함

**Comment by Kim-yejin-yj** [comment]
1. 문제 
[채소값 모니터링] 
input-> 대형마트/쿠팡, 마켓컬리 채소값/ 지난 날씨별 채소값  (그람 기준을 정해야할듯)
output-> 평균 채소값, 대형마트별 채소값 비교, 저번달 대비 값, 예측되는 채소값(날씨로 인해 변동되는 채소값)

2. 해결방법
solution (시스템 동작방식으로?)
*모델: 
*데이터: 대형마트 온라인몰에서 크롤링, 쿠팡, 마켓컬리, 네이버쇼핑, 옥션? ( 

3. 차별성 
다모아,에누리, 네이버쇼핑 가격비교 사이트가 있음. 하지만 다음달에 예측되는 채소값이 나오지 않는다. 저번달 대비 값도 나오지 않음. 평균 채소값 또한 나오지 않기 때문에 여기에 중점을 둬야함

**Comment by gyseong** [comment]
problem
자취를 시작한지 얼마안된 자취생이나 사회 초년생들은 자신이 얼마나 합리적인 소비를 하는지 모르고 농수산물을 구입한다. -> 그렇기 때문에 합리적인 소비를 위하여 자신이 소비하려는 채소의 시세를 알려주는 웹 또는 앱을 제작하기로 결정

**Comment by gyseong** [comment]
역할분담
ppt 제작 : 김예진
발표 대본 작성 : 조경서

이번주 토-일요일까지 작성 후 발표 연습
