### ISSUE TITLE
시스템 구성도 정의하기

### ISSUE THREAD

**Issue by gyseong** [JJOGyeongS/-vegetable_project#3]
시스템 구성도에 대해 의논합시다

**Comment by gyseong** [comment]
예상 결과물을 보면 채소의 가격이 비교가 아니라 값을 보여주고 그 값이 떨어졌나 올랐나만 보여주는건가요??

**Comment by gyseong** [comment]
그러면 분산 검색 엔진을 몇개 빼도 좋지 않을까요?

**Comment by Kim-yejin-yj** [comment]
아녀 대충 이런 느낌으로 만들거다 라는 예시 하나 만든거에요!
저 예시 밑에 대형마트랑 마켓컬리 상품 가격비교를 보여주긴 해야하지 않을까요?

**Comment by Kim-yejin-yj** [comment]
그러면 대형마트랑 마켓컬리는 크롤링해서 가져오는거라 무게를 기준 잡아서 한눈에 보기 쉽게 하기엔 어려울 것 같아서 가져오는건 "온라인몰에서는 이렇게 판다"랑 "상품권유"정도로 해야할 것 같아요

**Comment by Kim-yejin-yj** [comment]
상품권유는 바로가기 버튼으로 해당 사이트로 넘어가게 하는거로!

**Comment by Kim-yejin-yj** [comment]
가격비교하는 예상 결과물도 만들까요?

**Comment by gyseong** [comment]
밑에 그러면 가격비교도 하고 그래프로 전에는 어떻게 가격이 나왔는지도 보여주면 좋을거 같아요
