### ISSUE TITLE
요구사항 정의서 내용 정하기

### ISSUE THREAD

**Issue by Kim-yejin-yj** [JJOGyeongS/-vegetable_project#4]
세부적인 요구사항 정의서를 써봅시다

**Comment by gyseong** [comment]
일단 역할 분담을 하는게 좋을거 같아요
서론, 비기능적 
기능적, 인터페이스
이런식으로요

**Comment by Kim-yejin-yj** [comment]
넵 그럼 제가 서론이랑 비기능적 부분 할게요!

**Comment by gyseong** [comment]
저번에 피피티 발표하다 보니까 기능적 부분이 조금 부족한거 같아서 시세 예측으로 할 수 있는게 뭐가 있나 찾아보면 좋을거 같아요

**Comment by Kim-yejin-yj** [comment]
근데 우리 비기능적 요구사항에서 보안 요구사항에는 우리가 쓸 내용이 없는데 어떡할까요?.. 회원정보를 수집하진 않는데..

**Comment by Kim-yejin-yj** [comment]
시세예측을 활용해서 기능을 덧붙이자는 말씀이시죠?

**Comment by gyseong** [comment]
넵 맞아요 아니면 회원정보를 수집하지는 쪽으로 생각하지 말고 시간대별로 어떤 채소가 검색을 많이 했는지 정도 알게 하면 좋지 않을까요?

**Comment by gyseong** [comment]
그거 외에는 보안쪽은 딱히 건드릴게 없어 보이긴 해요

**Comment by Kim-yejin-yj** [comment]
오 그러면 그 기능에도 모니터링이 필요하겠네요

**Comment by gyseong** [comment]
그럼 그런 기능 추가할까요? 살짝 주제에 더 가까워진 느낌으로

**Comment by Kim-yejin-yj** [comment]
넵 좋아요!

**Comment by gyseong** [comment]
그러면 저가 기능적 요구사항이랑 인터페이스 작성하고 내일쯤 보내드릴게요

**Comment by Kim-yejin-yj** [comment]
경서님이 하시는게 더 많은거 같은데 제가 쓸게요!!

**Comment by gyseong** [comment]
엥 아니에요 저 기능쪽에 한줄 정도만 쓰면 될거 같아서 제가 할게요!
그러면 보안쪽만 남은거죠?

**Comment by Kim-yejin-yj** [comment]
앗 넵 보안 쪽은 일단 공백으로 둬볼까요?

**Comment by Kim-yejin-yj** [comment]
저도 그럼 주요 기능 설명에 덧붙일게요!!

**Comment by gyseong** [comment]
넵 알겠습니다! 내일까지 보내드릴게요
