### ISSUE TITLE
개발일정 짤까요?

### ISSUE THREAD

**Issue by Kim-yejin-yj** [JJOGyeongS/-vegetable_project#7]
간단하게 틀만 짜봤어요!
![image](https://user-images.githubusercontent.com/85615622/200155507-eab2d2c1-9208-4f76-8352-f88097994edd.png)

**Comment by gyseong** [comment]
넵 11/12일까지 모델 학습 시키겠습니다 근데 데이터 정제가 필요할거 같아요
