### ISSUE TITLE
발명설명서 관련 

### ISSUE THREAD

**Issue by gyseong** [JJOGyeongS/-vegetable_project#9]
교수님이 지적해주신 내용 중에 주장하려는 권리에 예측을 빼고 실시간 검색어 위주로 써야할 것 같습니다. 관련 논문이나 연구 찾아봐주세요

**Comment by gyseong** [comment]
@Kim-yejin-yj 여기다가 올려주세요!

**Comment by gyseong** [comment]
https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002330707
실시간 검색어 정보품질이 포털사이트 이용의도에 미치는 영향 연구

**Comment by gyseong** [comment]
실시간 검색어 구현 방법 및 참고자료
https://goodthings4me.tistory.com/749
https://react-style.selfhow.com/post/?id=1949

**Comment by Kim-yejin-yj** [comment]
https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002217605
실시간 이슈의 지속성 분석을 통한 사용자 정보 습득에 대한 특성과 패턴에 대한 연구

**Comment by Kim-yejin-yj** [comment]
경서님 논문은 경서님이 올리신 첫번째 논문이 우리가 말하려고 하는 바랑 같은것 같아요
